aliases:
  - &restore-cache
    key: dependencies-{{ checksum "build.gradle.kts" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
  - &save-cache
    key: dependencies-{{ checksum "build.gradle.kts" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
    paths:
      - ~/.gradle

version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/auto-truth
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache: *restore-cache
      - run:
          name: Build 'annotations' module
          command: ./gradlew :annotations:build --stacktrace
          no_output_timeout: 3m
      - run:
          name: Build 'processor' module
          command: ./gradlew :processor:build --stacktrace
          no_output_timeout: 3m
      - save_cache: *save-cache

  lint:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/auto-truth
    steps:
      - checkout
      - restore_cache: *restore-cache
      - run:
          name: Check code style and run lint
          command: ./gradlew :processor:check --stacktrace
          no_output_timeout: 3m
      - save_cache: *save-cache
      - store_artifacts:
          path: ./processor/reports/ktlint
          destination: ktlint
      - store_artifacts:
          path: ./processor/reports/detekt
          destination: detekt

  test:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/auto-truth
    steps:
      - checkout
      - restore_cache: *restore-cache
      - run:
          name: Setup Code Climate
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            ./cc-test-reporter -v
            ./cc-test-reporter before-build
          no_output_timeout: 3m
      - run:
          name: Run unit tests
          command: ./gradlew :processor:test :processor:jacocoTestReport --stacktrace
          no_output_timeout: 5m
      - run:
          name: Upload coverage report to Code Climate
          command: |
            PROJECT_ROOT=../../../..
            cd processor/src/main/kotlin
            $PROJECT_ROOT/cc-test-reporter format-coverage $PROJECT_ROOT/processor/build/reports/jacoco/jacoco.xml \
            --add-prefix processor/src/main/kotlin \
            -t jacoco \
            -o $PROJECT_ROOT/processor/build/coverage/codeclimate.json
            $PROJECT_ROOT/cc-test-reporter upload-coverage -i $PROJECT_ROOT/processor/build/coverage/codeclimate.json
          no_output_timeout: 3m
      - save_cache: *save-cache
      - store_test_results:
          path: ./processor/build/test-results/test
      - store_artifacts:
          path: ./processor/build/reports/test
          destination: spek
      - store_artifacts:
          path: ./processor/build/reports/jacoco
          destination: jacoco

workflows:
  version: 2
  build_and_test:
    jobs:
      - lint:
          filters:
            branches:
              ignore:
                - master
      - test
      - build:
          requires:
            - lint
            - test
